import PptxGenJS from 'pptxgenjs';

const logInfo = (msg) => {
    console.log(`[PPTX_GEN] ${msg}`);
    if (window.pocAddLog) window.pocAddLog(`[PPTX_GEN] ${msg}`, 'info');
};

const logError = (msg, err) => {
    console.error(`[PPTX_GEN] ${msg}`, err);
    if (window.pocAddLog) window.pocAddLog(`[PPTX_GEN] ${msg}: ${err ? err.message : ''}`, 'error');
};

export const generatePptx = async (spec) => {
    logInfo('Starting generatePptx...');
    try {
        const pptx = new PptxGenJS();

        // メタデータの設定
        pptx.title = spec.documentTitle || "Presentation";
        pptx.author = "Generated by Dify";
        pptx.subject = spec.documentTitle || "Generated Presentation";

        // レイアウト設定 (16:9を強制)
        pptx.layout = "LAYOUT_16x9";
        logInfo(`Layout configured: LAYOUT_16x9`);
        
        // テーマ設定
        const theme = spec.theme || {};

        // PptxGenJS用にカラーコード（#なしの6桁HEX）をサニタイズするヘルパー
        const sanitizeColor = (colorStr, fallback) => {
            if (!colorStr) return fallback;
            const cleaned = colorStr.replace('#', '');
            // 簡単なバリデーション (3桁または6桁のHex。PptxGenJSは基本的に6桁推奨)
            if (/^[0-9A-Fa-f]{6}$/.test(cleaned)) return cleaned.toUpperCase();
            if (/^[0-9A-Fa-f]{3}$/.test(cleaned)) {
                return cleaned.split('').map(c => c + c).join('').toUpperCase();
            }
            return fallback;
        };

        const mainFont = theme.fontFamilyBody || "Meiryo";
        const headerFont = theme.fontFamilyHeading || "Meiryo";
        
        const bgColor = sanitizeColor(theme.backgroundColor, "FFFFFF");
        const textColor = sanitizeColor(theme.textColor, "333333");
        
        // LLM指定値を最優先、無い場合はこちらの設定値をフォールバック
        const primaryColor = sanitizeColor(theme.primaryColor, "1C51DB"); // 鮮やかなブルー
        const secondaryColor = sanitizeColor(theme.secondaryColor, "EEF7FF"); // 極薄い青
        const accentColor = sanitizeColor(theme.accentColor, "FF5722");
        const mutedColor = sanitizeColor(theme.mutedTextColor, "888888");
        
        const lightGray = "F9F9FA";
        const borderGray = "E0E0E0";

        // 明度を判定して「暗い色」かどうかを返すヘルパー
        const isDarkColor = (hex) => {
            if (!hex) return false;
            // 正規化（#を除去）
            const color = hex.startsWith('#') ? hex.substring(1) : hex;
            if (color.length !== 6 && color.length !== 3) return false;
            
            let r, g, b;
            if (color.length === 6) {
                r = parseInt(color.substring(0, 2), 16);
                g = parseInt(color.substring(2, 4), 16);
                b = parseInt(color.substring(4, 6), 16);
            } else {
                r = parseInt(color[0] + color[0], 16);
                g = parseInt(color[1] + color[1], 16);
                b = parseInt(color[2] + color[2], 16);
            }
            // YIQ formula (明度)
            const yiq = (r * 299 + g * 587 + b * 114) / 1000;
            return yiq < 160;
        };

        const getContrastColor = (bgColor, defaultColor = textColor) => {
            return isDarkColor(bgColor) ? "FFFFFF" : defaultColor;
        };

        // マスター要素の定義 (16:9 = w:10.0 x h:5.625)
        pptx.defineSlideMaster({
            title: "DEFAULT_SLIDE",
            background: { color: bgColor },
            objects: [
                // 左上のアクセントライン
                { rect: { x: 0, y: 0.3, w: 0.1, h: 0.45, fill: { color: primaryColor } } },
                // 右上 ロゴプレースホルダー
                { text: { text: "● Company LOGO", options: { x: 7.5, y: 0.3, w: 2.0, h: 0.4, fontSize: 13, color: primaryColor, bold: true, align: "right", fontFace: headerFont } } },
                // フッター区切り線
                { line: { x: 0.3, y: 5.2, w: 9.4, h: 0, line: { color: borderGray, width: 1 } } },
                // 左下 コピーライト
                { text: { text: `Copyright © ${new Date().getFullYear()} All Rights Reserved.`, options: { x: 0.3, y: 5.3, w: 4.0, h: 0.3, fontSize: 9, fontFace: 'Arial', color: "888888", align: "left" } } }
            ],
            // ページ番号
            slideNumber: { x: 9.3, y: 5.3, color: "888888", fontSize: 10, fontFace: 'Arial' }
        });
        
        pptx.defineSlideMaster({
            title: "TITLE_SLIDE",
            background: { color: primaryColor },
            objects: [
                { rect: { x: 0, y: 4.5, w: 10.0, h: 1.125, fill: { color: "FFFFFF" } } }, // 底部の白い帯
                { text: { text: "● Company LOGO", options: { x: 7.5, y: 4.8, w: 2.0, h: 0.4, fontSize: 14, color: primaryColor, bold: true, align: "right", fontFace: headerFont } } },
            ]
        });

        // 共通見出し描画関数
        const renderHeader = (slide, title) => {
            slide.addText(title, { x: 0.3, y: 0.3, w: 8.0, h: 0.5, fontSize: 24, fontFace: headerFont, bold: true, color: "333333" });
        };

        // リード文描画関数（タイトル直下の導入テキスト）
        const renderLead = (slide, lead) => {
            if (!lead) return;
            slide.addText(lead, { x: 0.3, y: 0.9, w: 9.0, h: 0.4, fontSize: 14, fontFace: mainFont, color: mutedColor, italic: true });
        };

        // フッターノート描画関数（フッター線の上）
        const renderFooterNote = (slide, note) => {
            if (!note) return;
            slide.addText(note, { x: 0.3, y: 4.95, w: 9.0, h: 0.25, fontSize: 9, fontFace: mainFont, color: mutedColor, italic: true });
        };

        // コンテンツ開始Y座標（lead有無で変動）
        const getContentY = (hasLead) => hasLead ? 1.5 : 1.3;

        if (!spec.slides || !Array.isArray(spec.slides)) {
            throw new Error("No valid slides found in the PPTX specification.");
        }

        spec.slides.forEach((s, index) => {
            logInfo(`Processing slide ${index + 1}: type [${s.type}]`);
            let slide;
            const hasLead = !!s.lead;
            const cY = getContentY(hasLead);
            
            switch (s.type) {
                case "title":
                    slide = pptx.addSlide({ masterName: "TITLE_SLIDE" });
                    // Kicker（補助ラベル）または CONFIDENTIAL
                    slide.addText(s.kicker || "CONFIDENTIAL", { x: 0.5, y: 0.5, w: 3.0, h: 0.4, fontSize: 12, color: "FFFFFF", bold: true, align: "left", fontFace: 'Arial', letterSpacing: s.kicker ? 2 : 0 });
                    slide.addText(s.title || "", { x: 0.5, y: 2.0, w: 9.0, h: 1.5, fontSize: 44, fontFace: headerFont, bold: true, color: "FFFFFF", align: "left", breakLine: true });
                    if (s.subtitle) {
                        slide.addText(s.subtitle, { x: 0.5, y: 3.5, w: 9.0, h: 0.5, fontSize: 22, fontFace: mainFont, color: "FFFFFF", align: "left", breakLine: true });
                    }
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;
                    
                case "section":
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    // 大きなアクセント背景
                    slide.addShape(pptx.ShapeType.rect, { x: 0, y: 2.0, w: 10.0, h: 1.6, fill: { color: secondaryColor } });
                    slide.addShape(pptx.ShapeType.rect, { x: 0, y: 2.0, w: 0.15, h: 1.6, fill: { color: primaryColor } });
                    
                    slide.addText(s.title || "", { 
                        x: 0.5, y: 2.2, w: 9.0, h: 0.8, fontSize: 36, fontFace: headerFont, bold: true, 
                        color: isDarkColor(secondaryColor) ? "FFFFFF" : primaryColor, align: "left" 
                    });
                    if (s.subtitle) {
                        slide.addText(s.subtitle, { 
                            x: 0.5, y: 3.0, w: 9.0, h: 0.4, fontSize: 18, fontFace: mainFont, 
                            color: isDarkColor(secondaryColor) ? "FFFFFF" : textColor, align: "left" 
                        });
                    }
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                case "agenda":
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "目次");
                    renderLead(slide, s.lead);
                    if (s.items && s.items.length > 0) {
                        // 2カラムで目次を表示
                        const itemsPerCol = Math.ceil(s.items.length / 2);
                        s.items.forEach((item, i) => {
                            const isRight = i >= itemsPerCol;
                            const colNum = isRight ? 1 : 0;
                            const rowNum = isRight ? i - itemsPerCol : i;
                            const x = 0.5 + colNum * 4.8;
                            const y = cY + rowNum * 0.7;
                            
                            // 番号バッジ
                            slide.addText(String(i + 1).padStart(2, '0'), { x: x, y: y, w: 0.5, h: 0.4, fontSize: 18, fontFace: 'Arial', bold: true, color: primaryColor, align: "center" });
                            // タイトル
                            slide.addText(item, { x: x + 0.6, y: y, w: 3.5, h: 0.4, fontSize: 18, fontFace: mainFont, color: textColor, bold: true });
                            // 下線
                            slide.addShape(pptx.ShapeType.line, { x: x + 0.6, y: y + 0.4, w: 3.8, h: 0, line: { color: borderGray, width: 1, dashType: 'dash' } });
                        });
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                case "bullet":
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "");
                    renderLead(slide, s.lead);
                    
                    if (s.bullets && s.bullets.length > 0) {
                        const count = s.bullets.length;
                        const availH = 4.8 - cY;
                        const blockHeight = Math.min(0.8, availH / count);
                        s.bullets.forEach((b, i) => {
                            const y = cY + i * (blockHeight + 0.1);
                            // 四角い連番アイコン
                            slide.addShape(pptx.ShapeType.rect, { x: 0.5, y: y + 0.1, w: 0.4, h: 0.4, fill: { color: primaryColor } });
                            slide.addText(String(i + 1), { x: 0.5, y: y + 0.1, w: 0.4, h: 0.4, fontSize: 16, fontFace: 'Arial', color: "FFFFFF", bold: true, align: "center" });
                            // テキストボックス
                            slide.addText(b, { x: 1.1, y: y, w: 8.4, h: 0.6, fontSize: 18, fontFace: mainFont, color: textColor, valign: "middle", breakLine: true });
                        });
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                case "two-column":
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "");
                    renderLead(slide, s.lead);
                    
                    const renderCard = (data, xBase, w) => {
                        if (!data) return;
                        const cardH = 4.8 - cY;
                        slide.addShape(pptx.ShapeType.roundRect, { x: xBase, y: cY, w: w, h: cardH, fill: { color: lightGray }, line: { color: borderGray, width: 1 }, rectRadius: 0.2 });
                        if (data.heading) {
                            // 装飾ヘッダー
                            slide.addShape(pptx.ShapeType.rect, { x: xBase, y: cY, w: w, h: 0.6, fill: { color: primaryColor } });
                            slide.addText(data.heading, { x: xBase, y: cY + 0.1, w: w, h: 0.4, fontSize: 18, fontFace: headerFont, bold: true, color: "FFFFFF", align: "center" });
                        }
                        if (data.bodyPoints && data.bodyPoints.length > 0) {
                            const points = data.bodyPoints.map(p => ({ text: p, options: { bullet: true, breakLine: true } }));
                            slide.addText(points, { x: xBase + 0.2, y: cY + 0.8, w: w - 0.4, h: cardH - 1.0, fontSize: 16, fontFace: mainFont, color: textColor, valign: "top" });
                        }
                    };
                    
                    renderCard(s.left, 0.5, 4.3);
                    renderCard(s.right, 5.2, 4.3);
                    
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;
                    
                case "table":
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "");
                    renderLead(slide, s.lead);
                    
                    if (s.headers && s.rows) {
                        const tableData = [
                            s.headers.map(h => ({ 
                                text: h, 
                                options: { 
                                    bold: true, 
                                    fill: primaryColor, 
                                    color: getContrastColor(primaryColor, "FFFFFF"), 
                                    fontFace: headerFont, align: "center", valign: "middle" 
                                } 
                            }))
                        ];
                        s.rows.forEach((r, idx) => {
                            const rowBg = idx % 2 === 0 ? "FFFFFF" : lightGray;
                            tableData.push(r.map((cell, cIdx) => {
                                // 1列目は少し太く、色をつけるとヘッダーっぽくなる
                                const isFirstCol = cIdx === 0;
                                return { 
                                    text: String(cell), 
                                    options: { 
                                        fill: isFirstCol ? secondaryColor : rowBg, 
                                        color: isFirstCol ? getContrastColor(secondaryColor) : textColor,
                                        fontFace: mainFont, valign: "middle", bold: isFirstCol 
                                    } 
                                };
                            }));
                        });
                        const tableH = Math.min(3.5, 4.8 - cY);
                        slide.addTable(tableData, { x: 0.5, y: cY, w: 9.0, h: tableH, rowH: 0.5, fontSize: 14, border: { type: "solid", color: borderGray, pt: 1 } });
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;
                    
                case "chart-placeholder":
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "");
                    renderLead(slide, s.lead);
                    
                    let chartY = cY;
                    let chartH = 4.8 - cY;
                    
                    if (s.insight) {
                        slide.addShape(pptx.ShapeType.roundRect, { x: 0.5, y: cY, w: 9.0, h: 0.6, fill: { color: secondaryColor }, rectRadius: 0.2 });
                        slide.addText(`💡 Insight: ${s.insight}`, { 
                            x: 0.6, y: cY + 0.1, w: 8.8, h: 0.4, fontSize: 15, fontFace: mainFont, 
                            color: getContrastColor(secondaryColor, primaryColor), bold: true 
                        });
                        chartY = cY + 0.8;
                        chartH = 4.8 - chartY;
                    }
                    
                    if (s.series && s.categories) {
                        let pptxChartType = pptx.charts.BAR;
                        let chartOpts = { x: 0.5, y: chartY, w: 9.0, h: chartH, showLegend: true, legendPos: 't', chartColors: [primaryColor, accentColor, "00B0F0", "92D050", "FFC000"] };
                        
                        if (s.chartType === "line") pptxChartType = pptx.charts.LINE;
                        else if (s.chartType === "pie") pptxChartType = pptx.charts.PIE;
                        else if (s.chartType === "doughnut") pptxChartType = pptx.charts.DOUGHNUT;
                        else if (s.chartType === "stacked-bar") {
                            pptxChartType = pptx.charts.BAR;
                            chartOpts.barGrouping = 'stacked';
                        }
                        else if (s.chartType === "horizontal-bar") {
                            pptxChartType = pptx.charts.BAR;
                            chartOpts.barDir = 'bar';
                        }
                        
                        const chartData = s.series.map(ser => ({
                            name: ser.name,
                            labels: s.categories,
                            values: ser.values
                        }));
                        
                        slide.addChart(pptxChartType, chartData, chartOpts);
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;
                    
                case "summary":
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "要約");
                    renderLead(slide, s.lead);
                    
                    if (s.summaryPoints && s.summaryPoints.length > 0) {
                        const sumCardH = 4.8 - cY;
                        slide.addShape(pptx.ShapeType.roundRect, { x: 0.5, y: cY, w: 9.0, h: sumCardH, fill: { color: lightGray }, rectRadius: 0.2 });
                        // 左リボン装飾
                        slide.addShape(pptx.ShapeType.rect, { x: 0.5, y: cY + 0.2, w: 0.1, h: 0.8, fill: { color: primaryColor } });
                        slide.addText("キーポイント", { x: 0.8, y: cY + 0.3, w: 8.5, h: 0.5, fontSize: 20, fontFace: headerFont, bold: true, color: primaryColor });
                        
                        const sumData = s.summaryPoints.map((b, i) => ({ text: `✓  ${b}`, options: { breakLine: true } }));
                        slide.addText(sumData, { x: 0.8, y: cY + 0.9, w: 8.5, h: sumCardH - 1.2, fontSize: 18, fontFace: mainFont, color: textColor, align: "left", valign: "top", margin: 15 });
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                /* ========== 新規スライドタイプ ========== */

                case "toc-list":
                    // 目次一覧スライド
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "目次");
                    renderLead(slide, s.lead);
                    
                    if (s.items && s.items.length > 0) {
                        const tocRowH = Math.min(0.65, (4.8 - cY) / s.items.length);
                        s.items.forEach((item, i) => {
                            const y = cY + i * tocRowH;
                            // 番号（太字、プライマリ）
                            slide.addText(item.index || String(i + 1).padStart(2, '0'), { 
                                x: 0.5, y: y, w: 0.8, h: 0.4, fontSize: 20, fontFace: 'Arial', bold: true, color: primaryColor, align: "center" 
                            });
                            // ラベル（太字）
                            slide.addText(item.label, { 
                                x: 1.4, y: y, w: 6.0, h: 0.4, fontSize: 18, fontFace: mainFont, color: textColor, bold: true 
                            });
                            // ページ表記（右寄せ、ミューテッド）
                            slide.addText(item.page || '', { 
                                x: 8.0, y: y, w: 1.5, h: 0.4, fontSize: 14, fontFace: 'Arial', color: mutedColor, align: "right" 
                            });
                            // 点線区切り
                            slide.addShape(pptx.ShapeType.line, { 
                                x: 1.4, y: y + tocRowH * 0.8, w: 8.1, h: 0, line: { color: borderGray, width: 1, dashType: 'dot' } 
                            });
                        });
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                case "numbered-points":
                    // 番号付き説明スライド
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "");
                    renderLead(slide, s.lead);
                    
                    if (s.points && s.points.length > 0) {
                        const npCount = s.points.length;
                        const npBlockH = Math.min(1.0, (4.8 - cY) / npCount);
                        s.points.forEach((pt, i) => {
                            const y = cY + i * npBlockH;
                            // 大きな番号
                            slide.addText(pt.number || String(i + 1), { 
                                x: 0.5, y: y, w: 0.6, h: 0.5, fontSize: 26, fontFace: 'Arial', bold: true, color: primaryColor 
                            });
                            // 見出し（プライマリカラー太字 + 下線装飾）
                            slide.addText(pt.title, { 
                                x: 1.2, y: y, w: 8.3, h: 0.4, fontSize: 18, fontFace: headerFont, bold: true, color: primaryColor 
                            });
                            // 下線装飾
                            slide.addShape(pptx.ShapeType.line, { 
                                x: 1.2, y: y + 0.38, w: 8.3, h: 0, line: { color: primaryColor, width: 2 } 
                            });
                            // 説明文
                            slide.addText(pt.description, { 
                                x: 1.2, y: y + 0.45, w: 8.3, h: npBlockH - 0.55, fontSize: 14, fontFace: mainFont, color: textColor, valign: "top", breakLine: true 
                            });
                        });
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                case "feature-cards":
                    // 特長カードスライド
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "");
                    renderLead(slide, s.lead);
                    
                    if (s.cards && s.cards.length > 0) {
                        const cardCount = s.cards.length;
                        const totalW = 9.0;
                        const gap = 0.3;
                        const cardW = (totalW - gap * (cardCount - 1)) / cardCount;
                        const cardH = 4.8 - cY;
                        
                        s.cards.forEach((card, i) => {
                            const x = 0.5 + i * (cardW + gap);
                            // カード背景
                            slide.addShape(pptx.ShapeType.roundRect, { 
                                x: x, y: cY, w: cardW, h: cardH, 
                                fill: { color: secondaryColor }, line: { color: borderGray, width: 1 }, rectRadius: 0.15 
                            });
                            // アイコンプレースホルダー（丸い背景）
                            const iconRadius = 0.35;
                            slide.addShape(pptx.ShapeType.ellipse, { 
                                x: x + cardW / 2 - iconRadius, y: cY + 0.3, w: iconRadius * 2, h: iconRadius * 2, 
                                fill: { color: primaryColor, transparency: 85 } 
                            });
                            slide.addText(card.iconHint ? '★' : '★', { 
                                x: x, y: cY + 0.35, w: cardW, h: 0.6, fontSize: 22, color: primaryColor, align: "center", fontFace: headerFont 
                            });
                            // カードタイトル
                            slide.addText(card.title, { 
                                x: x + 0.15, y: cY + 1.3, w: cardW - 0.3, h: 0.4, fontSize: 16, fontFace: headerFont, bold: true, 
                                color: getContrastColor(secondaryColor), align: "center" 
                            });
                            // カード本文
                            slide.addText(card.description, { 
                                x: x + 0.15, y: cY + 1.8, w: cardW - 0.3, h: cardH - 2.3, fontSize: 12, fontFace: mainFont, 
                                color: getContrastColor(secondaryColor), align: "center", valign: "top", breakLine: true 
                            });
                            // キャプション
                            if (card.caption) {
                                slide.addText(card.caption, { 
                                    x: x + 0.15, y: cY + cardH - 0.4, w: cardW - 0.3, h: 0.3, fontSize: 9, fontFace: mainFont, 
                                    color: getContrastColor(secondaryColor, mutedColor), align: "center" 
                                });
                            }
                        });
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                case "pricing-table":
                    // 料金プラン比較スライド
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "");
                    renderLead(slide, s.lead);
                    
                    if (s.plans && s.featureRows) {
                        const plans = s.plans;
                        const featureRows = s.featureRows;
                        
                        // テーブルデータの構築（ヘッダー行 = 機能ラベル + プラン名と価格）
                        const headerRow = [
                            { text: '', options: { fill: bgColor, fontFace: mainFont } },
                            ...plans.map(plan => ({ 
                                text: `${plan.name}\n${plan.price}`, 
                                options: { 
                                    fill: plan.highlight ? primaryColor : secondaryColor, 
                                    color: plan.highlight ? "FFFFFF" : getContrastColor(secondaryColor), 
                                    fontFace: headerFont, bold: true, align: "center", valign: "middle",
                                    border: plan.highlight ? [{ type: "solid", color: primaryColor, pt: 2 }] : undefined
                                } 
                            }))
                        ];
                        
                        const tableData = [headerRow];
                        featureRows.forEach((row, idx) => {
                            const rowBg = idx % 2 === 0 ? "FFFFFF" : lightGray;
                            const cells = [
                                { text: row.label, options: { fill: rowBg, fontFace: mainFont, color: textColor, bold: true } },
                                ...(row.values || []).map((val, vIdx) => ({ 
                                    text: String(val), options: { fill: rowBg, fontFace: mainFont, color: textColor, align: "center", valign: "middle" } 
                                }))
                            ];
                            tableData.push(cells);
                        });
                        
                        const ptableH = Math.min(4.0, 4.8 - cY);
                        slide.addTable(tableData, { x: 0.5, y: cY, w: 9.0, h: ptableH, rowH: 0.45, fontSize: 12, border: { type: "solid", color: borderGray, pt: 1 } });
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                case "chart-analysis":
                    // グラフ分析スライド
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "");
                    renderLead(slide, s.lead);
                    
                    if (s.charts && s.charts.length > 0) {
                        const hasInsights = s.insights && s.insights.length > 0;
                        const chartAreaW = hasInsights ? 5.5 : 9.0;
                        
                        s.charts.forEach((chart, ci) => {
                            const chartCount = s.charts.length;
                            const perChartH = chartCount === 1 ? (4.8 - cY) : (4.8 - cY) / 2;
                            const cy = cY + ci * perChartH;
                            
                            let pptxChartType = pptx.charts.BAR;
                            let chartOpts = { 
                                x: 0.5, y: cy, w: chartAreaW, h: perChartH - 0.1, 
                                showLegend: true, legendPos: 't', 
                                chartColors: [primaryColor, accentColor, "00B0F0", "92D050", "FFC000"] 
                            };
                            
                            if (chart.chartType === "line") pptxChartType = pptx.charts.LINE;
                            else if (chart.chartType === "pie") pptxChartType = pptx.charts.PIE;
                            else if (chart.chartType === "doughnut") pptxChartType = pptx.charts.DOUGHNUT;
                            else if (chart.chartType === "stacked-bar") {
                                pptxChartType = pptx.charts.BAR;
                                chartOpts.barGrouping = 'stacked';
                            }
                            else if (chart.chartType === "horizontal-bar") {
                                pptxChartType = pptx.charts.BAR;
                                chartOpts.barDir = 'bar';
                            }
                            
                            if (chart.series && chart.categories) {
                                const chartData = chart.series.map(ser => ({
                                    name: ser.name,
                                    labels: chart.categories,
                                    values: ser.values
                                }));
                                slide.addChart(pptxChartType, chartData, chartOpts);
                            }
                        });
                        
                        // 洞察リスト（右側）
                        if (hasInsights) {
                            slide.addShape(pptx.ShapeType.roundRect, { 
                                x: 6.2, y: cY, w: 3.3, h: 4.8 - cY, 
                                fill: { color: secondaryColor }, rectRadius: 0.15 
                            });
                            slide.addText("分析の要点", { 
                                x: 6.4, y: cY + 0.2, w: 2.9, h: 0.4, fontSize: 16, fontFace: headerFont, bold: true, 
                                color: getContrastColor(secondaryColor, primaryColor) 
                            });
                            const insData = s.insights.map(ins => ({ text: `● ${ins}`, options: { breakLine: true } }));
                            slide.addText(insData, { 
                                x: 6.4, y: cY + 0.7, w: 2.9, h: 4.8 - cY - 1.0, fontSize: 12, fontFace: mainFont, 
                                color: getContrastColor(secondaryColor), valign: "top" 
                            });
                        }
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                case "profile-fact-sheet":
                    // 会社概要・人物紹介スライド
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "");
                    renderLead(slide, s.lead);
                    
                    if (s.facts && s.facts.length > 0) {
                        const hasProfile = !!s.profile;
                        const factsW = hasProfile ? 5.5 : 9.0;
                        
                        // ファクト一覧をテーブルで描画
                        const factTableData = s.facts.map((fact, idx) => {
                            const rowBg = idx % 2 === 0 ? "FFFFFF" : lightGray;
                            return [
                                { text: fact.label, options: { fill: rowBg, fontFace: mainFont, color: mutedColor, bold: true } },
                                { text: fact.value, options: { fill: rowBg, fontFace: mainFont, color: textColor } }
                            ];
                        });
                        const factTableH = Math.min(4.8 - cY, s.facts.length * 0.5);
                        slide.addTable(factTableData, { 
                            x: 0.5, y: cY, w: factsW, h: factTableH, rowH: 0.4, fontSize: 12, 
                            border: { type: "solid", color: borderGray, pt: 1 },
                            colW: [1.8, factsW - 1.8]
                        });
                        
                        // プロフィールカード（右側）
                        if (hasProfile) {
                            const prof = s.profile;
                            const profH = 4.8 - cY;
                            slide.addShape(pptx.ShapeType.roundRect, { 
                                x: 6.2, y: cY, w: 3.3, h: profH, 
                                fill: { color: secondaryColor }, line: { color: borderGray, width: 1 }, rectRadius: 0.15 
                            });
                            // 役職ヘッダー
                            slide.addText(prof.role || '代表者', { 
                                x: 6.2, y: cY + 0.2, w: 3.3, h: 0.4, fontSize: 14, fontFace: headerFont, bold: true, 
                                color: getContrastColor(secondaryColor, primaryColor), align: "center" 
                            });
                            // 画像プレースホルダー
                            slide.addShape(pptx.ShapeType.roundRect, { 
                                x: 7.2, y: cY + 0.7, w: 1.3, h: 1.3, 
                                fill: { color: borderGray }, rectRadius: 0.1 
                            });
                            slide.addText('👤', { 
                                x: 7.2, y: cY + 0.9, w: 1.3, h: 0.9, fontSize: 28, align: "center", color: "999999" 
                            });
                            // 名前
                            slide.addText(prof.name, { 
                                x: 6.4, y: cY + 2.2, w: 2.9, h: 0.4, fontSize: 16, fontFace: headerFont, bold: true, 
                                color: getContrastColor(secondaryColor), align: "center" 
                            });
                            // Bio
                            slide.addText(prof.bio, { 
                                x: 6.4, y: cY + 2.7, w: 2.9, h: profH - 3.0, fontSize: 10, fontFace: mainFont, 
                                color: getContrastColor(secondaryColor), align: "center", valign: "top", breakLine: true 
                            });
                        }
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                default:
                    // 未対応タイプのフォールバック
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "スライド");
                    renderLead(slide, s.lead);
                    slide.addText(`[未対応スライドタイプ: ${s.type}]`, { x: 0.5, y: 2.0, w: 9.0, h: 1.0, fontSize: 18, fontFace: mainFont, color: mutedColor, align: "center" });
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;
            }
        });

        const safeTitle = (spec.documentTitle || 'presentation').replace(/[\\/:*?"<>|]/g, '_');
        logInfo(`Saving PPTX file: ${safeTitle}.pptx`);
        await pptx.writeFile({ fileName: `${safeTitle}.pptx` });
        logInfo('PPTX generation completed successfully.');
    } catch (e) {
        logError('Error during PPTX generation', e);
        throw e;
    }
};
