import PptxGenJS from 'pptxgenjs';

const logInfo = (msg) => {
    console.log(`[PPTX_GEN] ${msg}`);
    if (window.pocAddLog) window.pocAddLog(`[PPTX_GEN] ${msg}`, 'info');
};

const logError = (msg, err) => {
    console.error(`[PPTX_GEN] ${msg}`, err);
    if (window.pocAddLog) window.pocAddLog(`[PPTX_GEN] ${msg}: ${err ? err.message : ''}`, 'error');
};

export const generatePptx = async (spec) => {
    logInfo('Starting generatePptx...');
    try {
        const pptx = new PptxGenJS();

        // メタデータの設定
        pptx.title = spec.documentTitle || "Presentation";
        pptx.author = "Generated by Dify";
        pptx.subject = spec.documentTitle || "Generated Presentation";

        // レイアウト設定 (16:9を強制, 10.0 x 5.625 inches)
        pptx.layout = "LAYOUT_16x9";
        logInfo(`Layout configured: LAYOUT_16x9`);

        // テーマ設定
        const theme = spec.theme || {};

        // PptxGenJS用にカラーコード（#なしの6桁HEX）をサニタイズするヘルパー
        const sanitizeColor = (colorStr, fallback) => {
            if (!colorStr) return fallback;
            const cleaned = colorStr.replace('#', '');
            if (/^[0-9A-Fa-f]{6}$/.test(cleaned)) return cleaned.toUpperCase();
            if (/^[0-9A-Fa-f]{3}$/.test(cleaned)) {
                return cleaned.split('').map(c => c + c).join('').toUpperCase();
            }
            return fallback;
        };

        const mainFont = theme.fontFamilyBody || "Meiryo";
        const headerFont = theme.fontFamilyHeading || "Meiryo";

        // sample.html ベースのモダンなデフォルトカラーパレット
        const bgColor = sanitizeColor(theme.backgroundColor, "FFFFFF");
        const textColor = sanitizeColor(theme.textColor, "1E293B"); // color-body

        const primaryColor = sanitizeColor(theme.primaryColor, "0F172A");   // color-primary (濃いスレート)
        const secondaryColor = sanitizeColor(theme.secondaryColor, "F1F5F9"); // color-bg-accent (薄いグレー)
        const accentColor = sanitizeColor(theme.accentColor, "334155");     // color-accent
        const mutedColor = sanitizeColor(theme.mutedTextColor, "94A3B8");   // color-muted

        const borderColor = sanitizeColor(theme.borderColor || theme.borderGray, "E2E8F0"); // color-border

        // 明度判定ヘルパー
        const isDarkColor = (hex) => {
            if (!hex) return false;
            const color = hex.startsWith('#') ? hex.substring(1) : hex;
            if (color.length !== 6 && color.length !== 3) return false;

            let r, g, b;
            if (color.length === 6) {
                r = parseInt(color.substring(0, 2), 16);
                g = parseInt(color.substring(2, 4), 16);
                b = parseInt(color.substring(4, 6), 16);
            } else {
                r = parseInt(color[0] + color[0], 16);
                g = parseInt(color[1] + color[1], 16);
                b = parseInt(color[2] + color[2], 16);
            }
            const yiq = (r * 299 + g * 587 + b * 114) / 1000;
            return yiq < 160;
        };

        const getContrastColor = (bgColorHex, defaultColor = textColor) => {
            return isDarkColor(bgColorHex) ? "FFFFFF" : defaultColor;
        };

        // ==========================================
        // グラデーション背景の動的生成ヘルパー
        // ==========================================

        // 指定したHEXカラーを自然に明るくする関数 (行先の色を自動計算)
        const getGradientEndColor = (hex, lightenRatio = 0.25) => {
            let r = parseInt(hex.substring(0, 2), 16);
            let g = parseInt(hex.substring(2, 4), 16);
            let b = parseInt(hex.substring(4, 6), 16);

            r = Math.min(255, Math.floor(r + (255 - r) * lightenRatio));
            g = Math.min(255, Math.floor(g + (255 - g) * lightenRatio));
            b = Math.min(255, Math.floor(b + (255 - b) * lightenRatio));

            return [r, g, b].map(x => x.toString(16).padStart(2, '0')).join('').toUpperCase();
        };

        // Canvasを使ってグラデーション画像をBase64で生成
        const generateGradientBackground = (colorStart, colorEnd) => {
            const canvas = document.createElement('canvas');
            canvas.width = 1280;
            canvas.height = 720;
            const ctx = canvas.getContext('2d');

            // 左上(0,0)から右下(1280,720)への線形グラデーション
            const gradient = ctx.createLinearGradient(0, 0, 1280, 720);
            gradient.addColorStop(0, `#${colorStart}`);
            gradient.addColorStop(1, `#${colorEnd}`);

            ctx.fillStyle = gradient;
            ctx.fillRect(0, 0, 1280, 720);

            return canvas.toDataURL('image/jpeg', 0.8);
        };

        // プライマリカラーから自動的に終端色を算出し、グラデーション画像を生成
        const gradientEndColor = getGradientEndColor(primaryColor, 0.25);
        const titleGradientBase64 = generateGradientBackground(primaryColor, gradientEndColor);

        // ==========================================
        // マスター要素の定義
        // ==========================================
        pptx.defineSlideMaster({
            title: "DEFAULT_SLIDE",
            background: { color: bgColor },
            objects: [],
            slideNumber: { x: 9.3, y: 5.3, color: mutedColor, fontSize: 10, fontFace: mainFont }
        });

        pptx.defineSlideMaster({
            title: "TITLE_SLIDE",
            // 生成したグラデーション画像を背景に設定
            background: { data: titleGradientBase64 },
            objects: []
        });

        // 共通見出し描画関数 (Eyebrow + Title + Rule)
        const renderHeader = (slide, title, eyebrowText = "SECTION") => {
            // Eyebrow (Kicker)
            slide.addText(eyebrowText.toUpperCase(), {
                x: 0.5, y: 0.35, w: 9.0, h: 0.2,
                fontSize: 11, fontFace: mainFont, bold: true, color: accentColor, charSpacing: 2
            });
            // Main Title
            slide.addText(title, {
                x: 0.5, y: 0.55, w: 9.0, h: 0.5,
                fontSize: 28, fontFace: headerFont, bold: true, color: primaryColor
            });
            // 底部の境界線
            slide.addShape(pptx.ShapeType.line, {
                x: 0.5, y: 1.1, w: 9.0, h: 0,
                line: { color: borderColor, width: 2 }
            });
        };

        // リード文描画関数
        const renderLead = (slide, lead) => {
            if (!lead) return;
            slide.addText(lead, {
                x: 0.5, y: 1.25, w: 9.0, h: 0.4,
                fontSize: 14, fontFace: mainFont, color: textColor
            });
        };

        // フッターノート描画関数
        const renderFooterNote = (slide, note) => {
            if (!note) return;
            slide.addText(note, {
                x: 0.5, y: 5.0, w: 9.0, h: 0.25,
                fontSize: 10, fontFace: mainFont, color: mutedColor
            });
        };

        // コンテンツ開始Y座標
        const getContentY = (hasLead) => hasLead ? 1.75 : 1.35;

        if (!spec.slides || !Array.isArray(spec.slides)) {
            throw new Error("No valid slides found in the PPTX specification.");
        }

        spec.slides.forEach((s, index) => {
            logInfo(`Processing slide ${index + 1}: type [${s.type}]`);
            let slide;
            const hasLead = !!s.lead;
            const cY = getContentY(hasLead);

            switch (s.type) {
                case "title":
                    slide = pptx.addSlide({ masterName: "TITLE_SLIDE" });

                    // 背景が濃色のため、文字色は白（または透明度のある白）を使用
                    const titleTextColor = "FFFFFF";
                    const subtitleTextColor = "E2E8F0"; // rgba(255, 255, 255, 0.82) 相当の少しミュートされた白

                    // ==========================================
                    // 上部ブロック (Kicker, Title, Subtitle)
                    // ==========================================

                    // 1. Kicker (例: MODERN TEMPLATE)
                    const kickerText = s.kicker || "CONFIDENTIAL";
                    // 文字数に応じて枠の幅を動的に計算 (1文字約0.11インチ + 左右余白・ドット分0.55インチ)
                    const kickerW = Math.max(2.0, (kickerText.length * 0.11) + 0.55);

                    // 1-A. Kickerの枠線と背景 (ピル型)
                    slide.addShape(pptx.ShapeType.roundRect, {
                        x: 0.5, y: 0.5, w: kickerW, h: 0.4,
                        fill: { color: "FFFFFF", transparency: 90 },
                        line: { color: titleTextColor, width: 1 },
                        rectRadius: 0.2
                    });
                    // 1-B. Kickerの左端の小さなドット
                    slide.addShape(pptx.ShapeType.ellipse, {
                        x: 0.65, y: 0.65, w: 0.1, h: 0.1,
                        fill: { color: titleTextColor }
                    });
                    // 1-C. Kickerのテキスト (ドットの右側から開始し、確保した幅を割り当てる)
                    slide.addText(kickerText, {
                        x: 0.85, y: 0.5, w: kickerW - 0.4, h: 0.4,
                        fontSize: 11, fontFace: mainFont, bold: true, color: titleTextColor, charSpacing: 2, align: "left", valign: "middle"
                    });

                    // 2. Main Title
                    slide.addText(s.title || "スライドタイトル", {
                        x: 0.5, y: 1.2, w: 9.0, h: 1.5,
                        fontSize: 44, fontFace: headerFont, bold: true, color: titleTextColor, align: "left", valign: "top", breakLine: true
                    });

                    // 3. Subtitle
                    if (s.subtitle) {
                        slide.addText(s.subtitle, {
                            // 幅を 6.5 に絞ることで右側に意図的な余白を作り、自然な改行を促す
                            x: 0.5, y: 2.8, w: 6.5, h: 1.0,
                            fontSize: 18, fontFace: mainFont, color: subtitleTextColor, align: "left", valign: "top", breakLine: true, lineSpacing: 24
                        });
                    }

                    // ==========================================
                    // 下部ブロック (Hero Ribbon, Presenter Info)
                    // ==========================================

                    // 4. Hero Ribbon
                    const heroTags = s.heroTags || [];
                    let currentTagX = 0.5;
                    heroTags.forEach(tag => {
                        // 文字の長さに応じて幅を概算 (1文字あたり約0.14インチ + 左右パディング)
                        const tagW = tag.length * 0.14 + 0.3;

                        // タグの枠線 (ピル型)
                        slide.addShape(pptx.ShapeType.roundRect, {
                            x: currentTagX, y: 4.5, w: tagW, h: 0.38,
                            line: { color: subtitleTextColor, width: 1 },
                            rectRadius: 0.19
                        });
                        // タグのテキスト
                        slide.addText(tag, {
                            x: currentTagX, y: 4.5, w: tagW, h: 0.38,
                            fontSize: 11, fontFace: mainFont, bold: true, color: titleTextColor, align: "center", valign: "middle"
                        });
                        currentTagX += tagW + 0.15; // 次のタグの開始位置へシフト
                    });

                    // 5. Presenter Info (右下揃え)
                    const presenterLines = [
                        spec.documentTitle || "Reusable Sample Code",
                        "Modern Slide HTML Template",
                        new Date().getFullYear().toString()
                    ];
                    slide.addText(presenterLines.join('\n'), {
                        x: 6.5, y: 4.2, w: 3.0, h: 0.8,
                        fontSize: 12, fontFace: mainFont, color: subtitleTextColor, align: "right", valign: "bottom", breakLine: true, lineSpacing: 18
                    });

                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                case "section":
                    // closing slide 風のクリーンなレイアウト
                    slide = pptx.addSlide({ masterName: "TITLE_SLIDE" });

                    // 中央の大きなカード
                    slide.addShape(pptx.ShapeType.roundRect, {
                        x: 1.0, y: 1.2, w: 8.0, h: 3.2,
                        fill: { color: secondaryColor }, line: { color: borderColor, width: 1 }, rectRadius: 0.05
                    });

                    slide.addText("SECTION", {
                        x: 1.5, y: 1.5, w: 7.0, h: 0.3,
                        fontSize: 11, fontFace: mainFont, bold: true, color: accentColor, charSpacing: 2
                    });

                    slide.addText(s.title || "", {
                        x: 1.5, y: 1.9, w: 7.0, h: 0.8,
                        fontSize: 34, fontFace: headerFont, bold: true, color: primaryColor, align: "left"
                    });
                    if (s.subtitle) {
                        slide.addText(s.subtitle, {
                            x: 1.5, y: 2.8, w: 7.0, h: 1.0,
                            fontSize: 16, fontFace: mainFont, color: textColor, align: "left", valign: "top"
                        });
                    }
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                case "agenda":
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });

                    // ==========================================
                    // 1. アジェンダ専用リッチヘッダー (左右分割・下線付き)
                    // ==========================================
                    slide.addText("AGENDA", {
                        x: 0.5, y: 0.35, w: 4.5, h: 0.2,
                        fontSize: 11, fontFace: mainFont, bold: true, color: accentColor, charSpacing: 2
                    });
                    slide.addText(s.title || "Agenda", {
                        x: 0.5, y: 0.55, w: 4.5, h: 0.5,
                        fontSize: 28, fontFace: headerFont, bold: true, color: primaryColor
                    });
                    if (s.lead) {
                        // リード文を右側に配置
                        slide.addText(s.lead, {
                            x: 5.2, y: 0.65, w: 4.3, h: 0.4,
                            fontSize: 13, fontFace: mainFont, color: textColor, align: "left", valign: "bottom", breakLine: true
                        });
                    }
                    // ヘッダー領域全体の下線
                    slide.addShape(pptx.ShapeType.line, {
                        x: 0.5, y: 1.15, w: 9.0, h: 0,
                        line: { color: borderColor, width: 2 }
                    });

                    // ==========================================
                    // 2. リスト領域 (動的カラムとリッチアイコン)
                    // ==========================================
                    const contentY = 1.4;
                    const availableH = 3.6; // フッターまでの利用可能高さ

                    if (s.items && s.items.length > 0) {
                        // 5項目以下の場合は1カラム、6項目以上の場合は2カラムに切り替え
                        const isTwoCol = s.items.length > 5;
                        const itemsPerCol = isTwoCol ? Math.ceil(s.items.length / 2) : s.items.length;

                        // カラムに応じた幅とアイテムの高さを計算
                        const colW = isTwoCol ? 4.3 : 9.0;
                        const itemH = Math.min(0.9, availableH / itemsPerCol); // 最大高さを制限

                        s.items.forEach((item, i) => {
                            const isRight = isTwoCol && i >= itemsPerCol;
                            const colNum = isRight ? 1 : 0;
                            const rowNum = isRight ? i - itemsPerCol : i;

                            const x = 0.5 + colNum * 4.7;
                            const y = contentY + rowNum * itemH;

                            // A. 番号バッジ (ドロップシャドウ付き円)
                            slide.addShape(pptx.ShapeType.ellipse, {
                                x: x, y: y + 0.15, w: 0.45, h: 0.45,
                                fill: { color: primaryColor },
                                shadow: { type: 'outer', blur: 6, offset: 2, opacity: 0.25, color: primaryColor }
                            });
                            // B. 白抜き数字
                            slide.addText(String(i + 1), {
                                x: x, y: y + 0.15, w: 0.45, h: 0.45,
                                fontSize: 14, fontFace: mainFont, bold: true, color: "FFFFFF", align: "center", valign: "middle"
                            });

                            // C. タイトル (太字)
                            const itemTitle = typeof item === 'object' && item !== null ? (item.title || "") : String(item);
                            slide.addText(itemTitle, {
                                x: x + 0.6, y: y + 0.1, w: colW - 0.6, h: 0.3,
                                fontSize: 16, fontFace: headerFont, color: primaryColor, bold: true, valign: "bottom"
                            });

                            // D. 説明文 (細字ミュートカラー)
                            const itemDesc = typeof item === 'object' && item !== null ? item.desc : "";
                            if (itemDesc) {
                                slide.addText(itemDesc, {
                                    x: x + 0.6, y: y + 0.4, w: colW - 0.6, h: 0.3,
                                    fontSize: 12, fontFace: mainFont, color: mutedColor, valign: "top", breakLine: true
                                });
                            }

                            // E. 区切り線 (最後のアイテム以外に引く)
                            if (rowNum < itemsPerCol - 1) {
                                slide.addShape(pptx.ShapeType.line, {
                                    x: x, y: y + itemH - 0.05, w: colW, h: 0,
                                    line: { color: borderColor, width: 1 }
                                });
                            }
                        });
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                case "bullet":
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });

                    // ==========================================
                    // 1. リッチヘッダー (Content用)
                    // ==========================================
                    const eyebrow = s.eyebrow || "CONTENT";
                    slide.addText(eyebrow, {
                        x: 0.5, y: 0.35, w: 4.5, h: 0.2,
                        fontSize: 11, fontFace: mainFont, bold: true, color: accentColor, charSpacing: 2
                    });
                    slide.addText(s.title || "コンテンツタイトル", {
                        x: 0.5, y: 0.55, w: 4.5, h: 0.5,
                        fontSize: 28, fontFace: headerFont, bold: true, color: primaryColor
                    });
                    if (s.lead) {
                        slide.addText(s.lead, {
                            x: 5.2, y: 0.65, w: 4.3, h: 0.4,
                            fontSize: 13, fontFace: mainFont, color: textColor, align: "left", valign: "bottom", breakLine: true
                        });
                    }
                    slide.addShape(pptx.ShapeType.line, {
                        x: 0.5, y: 1.15, w: 9.0, h: 0,
                        line: { color: borderColor, width: 2 }
                    });

                    // ==========================================
                    // 2. 情報量に応じたレイアウトの自動計算
                    // ==========================================
                    let mainX = 0.5;
                    let mainY = 1.35;
                    let mainW = 9.0;
                    let mainH = 3.45; // 利用可能な最大高さ

                    const hasMetrics = s.metrics && s.metrics.length > 0;
                    const hasPointCards = s.pointCards && s.pointCards.length > 0;

                    let metricsY = 0;
                    let metricsH = 0.85;

                    if (hasMetrics) {
                        mainH -= (metricsH + 0.15);
                        metricsY = mainY + mainH + 0.15;
                    }

                    let pointsX = 0;
                    let pointsW = 3.3;

                    if (hasPointCards) {
                        mainW -= (pointsW + 0.2);
                        pointsX = mainX + mainW + 0.2;
                    }

                    // ==========================================
                    // 3. メインパネル (左側 または 全幅)
                    // ==========================================
                    slide.addShape(pptx.ShapeType.roundRect, {
                        x: mainX, y: mainY, w: mainW, h: mainH,
                        fill: { color: "FFFFFF" }, line: { color: borderColor, width: 1 }, rectRadius: 0.05
                    });

                    let contentYOffset = mainY + 0.2;
                    const innerW = mainW - 0.4;
                    const innerX = mainX + 0.2;

                    if (s.panelLead) {
                        slide.addText(s.panelLead, {
                            x: innerX, y: contentYOffset, w: innerW, h: 0.6,
                            fontSize: 15, fontFace: mainFont, color: accentColor, valign: "top", breakLine: true
                        });
                        contentYOffset += 0.65;
                    }

                    // 箇条書きリスト または 番号付きリスト
                    if (s.bullets && s.bullets.length > 0) {
                        const isNumbered = s.isNumbered === true;

                        const bulletTexts = s.bullets.map(b => ({
                            text: b,
                            options: {
                                bullet: isNumbered ? { type: 'number' } : { type: 'character', code: '2022' },
                                breakLine: true
                            }
                        }));

                        slide.addText(bulletTexts, {
                            x: innerX, y: contentYOffset, w: innerW, h: (mainY + mainH) - contentYOffset - 0.1,
                            fontSize: 14, fontFace: mainFont, color: textColor, valign: "top", lineSpacing: 18
                        });
                    }

                    // ==========================================
                    // 4. サブパネル領域 (右側ポイントカード)
                    // ==========================================
                    if (hasPointCards) {
                        slide.addShape(pptx.ShapeType.roundRect, {
                            x: pointsX, y: mainY, w: pointsW, h: mainH,
                            fill: { color: secondaryColor }, rectRadius: 0.05
                        });

                        const pCount = s.pointCards.length;
                        const availableCardAreaH = mainH - 0.3;
                        const cardH = Math.min((availableCardAreaH - (0.15 * (pCount - 1))) / pCount, 1.2);

                        s.pointCards.forEach((pc, i) => {
                            const cY = mainY + 0.15 + i * (cardH + 0.15);

                            const labelText = pc.label || "POINT";
                            const labelW = Math.max(0.8, labelText.length * 0.1 + 0.2);
                            slide.addShape(pptx.ShapeType.roundRect, {
                                x: pointsX + 0.15, y: cY, w: labelW, h: 0.25,
                                fill: { color: primaryColor, transparency: 85 },
                                rectRadius: 0.12
                            });
                            slide.addText(labelText, {
                                x: pointsX + 0.15, y: cY + 0.02, w: labelW, h: 0.25,
                                fontSize: 9, fontFace: mainFont, bold: true, color: primaryColor, align: "center", valign: "middle"
                            });

                            slide.addShape(pptx.ShapeType.roundRect, {
                                x: pointsX + 0.15, y: cY + 0.35, w: pointsW - 0.3, h: cardH - 0.35,
                                fill: { color: "FFFFFF" }, line: { color: borderColor, width: 1 }, rectRadius: 0.05
                            });
                            slide.addShape(pptx.ShapeType.rect, {
                                x: pointsX + 0.15, y: cY + 0.35, w: 0.05, h: cardH - 0.35,
                                fill: { color: primaryColor }
                            });

                            slide.addText(pc.title || "", {
                                x: pointsX + 0.25, y: cY + 0.4, w: pointsW - 0.45, h: 0.2,
                                fontSize: 13, fontFace: headerFont, bold: true, color: primaryColor, valign: "middle"
                            });

                            if (pc.desc) {
                                slide.addText(pc.desc, {
                                    x: pointsX + 0.25, y: cY + 0.65, w: pointsW - 0.45, h: cardH - 0.7,
                                    fontSize: 12, fontFace: mainFont, color: textColor, valign: "top", breakLine: true
                                });
                            }
                        });
                    }

                    // ==========================================
                    // 5. メトリクス領域 (下部ナンバーカード)
                    // ==========================================
                    if (hasMetrics) {
                        const mCount = s.metrics.length;
                        const gap = 0.15;
                        const mCardW = (9.0 - gap * (mCount - 1)) / mCount;

                        s.metrics.forEach((m, i) => {
                            const mX = 0.5 + i * (mCardW + gap);

                            slide.addShape(pptx.ShapeType.roundRect, {
                                x: mX, y: metricsY, w: mCardW, h: metricsH,
                                fill: { color: secondaryColor }, line: { color: borderColor, width: 1 }, rectRadius: 0.05
                            });

                            slide.addText(m.value || "0", {
                                x: mX + 0.15, y: metricsY + 0.1, w: mCardW - 0.3, h: 0.4,
                                fontSize: 26, fontFace: 'Arial', bold: true, color: primaryColor, align: "left"
                            });

                            slide.addText(m.label || "METRIC", {
                                x: mX + 0.15, y: metricsY + 0.5, w: mCardW - 0.3, h: 0.25,
                                fontSize: 10, fontFace: mainFont, color: mutedColor, align: "left", valign: "top", charSpacing: 1
                            });
                        });
                    }

                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                case "two-column": { // ← エラー防止のためブロックスコープを作成
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });

                    // ==========================================
                    // 1. リッチヘッダー
                    // ==========================================
                    const tcEyebrow = s.eyebrow || "COMPARISON";
                    slide.addText(tcEyebrow, {
                        x: 0.5, y: 0.35, w: 4.5, h: 0.2,
                        fontSize: 11, fontFace: mainFont, bold: true, color: accentColor, charSpacing: 2
                    });
                    slide.addText(s.title || "比較・対比", {
                        x: 0.5, y: 0.55, w: 4.5, h: 0.5,
                        fontSize: 28, fontFace: headerFont, bold: true, color: primaryColor
                    });
                    if (s.lead) {
                        slide.addText(s.lead, {
                            x: 5.2, y: 0.65, w: 4.3, h: 0.4,
                            fontSize: 13, fontFace: mainFont, color: textColor, align: "left", valign: "bottom", breakLine: true
                        });
                    }
                    slide.addShape(pptx.ShapeType.line, {
                        x: 0.5, y: 1.15, w: 9.0, h: 0,
                        line: { color: borderColor, width: 2 }
                    });

                    // ==========================================
                    // 2. 左右カラムの描画ロジック
                    // ==========================================
                    // エラー原因だった `const cY = 1.4;` を削除し、外部の cY を利用
                    const cardH = 4.8 - cY; // フッターまでの高さを自動計算
                    const cardW = 4.4;

                    const renderCol = (data, isRight) => {
                        if (!data) return;
                        const xBase = isRight ? 5.1 : 0.5;

                        const cardBgColor = isRight ? "FFFFFF" : secondaryColor;
                        const cardLineColor = isRight ? borderColor : null;

                        const tagText = data.tag || (isRight ? "GOOD / AFTER" : "BAD / BEFORE");
                        const tagBgColor = isRight ? primaryColor : accentColor;

                        const rectOpts = {
                            x: xBase, y: cY, w: cardW, h: cardH,
                            fill: { color: cardBgColor },
                            rectRadius: 0.05
                        };
                        if (cardLineColor) rectOpts.line = { color: cardLineColor, width: 1 };
                        slide.addShape(pptx.ShapeType.roundRect, rectOpts);

                        const tagW = Math.max(1.0, (tagText.length * 0.1) + 0.3);
                        slide.addShape(pptx.ShapeType.roundRect, {
                            x: xBase + 0.3, y: cY + 0.3, w: tagW, h: 0.25,
                            fill: { color: tagBgColor },
                            rectRadius: 0.12
                        });
                        slide.addText(tagText, {
                            x: xBase + 0.3, y: cY + 0.32, w: tagW, h: 0.25,
                            fontSize: 9, fontFace: mainFont, bold: true, color: "FFFFFF", align: "center", valign: "middle", charSpacing: 1
                        });

                        let textY = cY + 0.75;
                        if (data.heading) {
                            slide.addText(data.heading, {
                                x: xBase + 0.3, y: textY, w: cardW - 0.6, h: 0.3,
                                fontSize: 16, fontFace: headerFont, bold: true, color: primaryColor
                            });
                            textY += 0.35;

                            slide.addShape(pptx.ShapeType.line, {
                                x: xBase + 0.3, y: textY, w: cardW - 0.6, h: 0,
                                line: { color: borderColor, width: 1 }
                            });
                            textY += 0.2;
                        }

                        if (data.bodyPoints && data.bodyPoints.length > 0) {
                            const isNumbered = data.isNumbered === true;
                            const points = data.bodyPoints.map(p => ({
                                text: p,
                                options: {
                                    bullet: isNumbered ? { type: 'number' } : { type: 'character', code: '2022' },
                                    breakLine: true
                                }
                            }));
                            slide.addText(points, {
                                x: xBase + 0.3, y: textY, w: cardW - 0.6, h: (cY + cardH) - textY - 0.2,
                                fontSize: 14, fontFace: mainFont, color: textColor, valign: "top", lineSpacing: 18
                            });
                        }
                    };

                    renderCol(s.left, false);
                    renderCol(s.right, true);

                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;
                } // ← ブロックスコープの閉じ忘れにご注意ください

                case "table":
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "", "Data Table");
                    renderLead(slide, s.lead);

                    if (s.headers && s.rows) {
                        const tableData = [
                            s.headers.map(h => ({
                                text: h,
                                options: {
                                    bold: true, fill: secondaryColor, color: primaryColor,
                                    fontFace: headerFont, align: "center", valign: "middle"
                                }
                            }))
                        ];
                        s.rows.forEach((r, idx) => {
                            tableData.push(r.map((cell, cIdx) => {
                                const isFirstCol = cIdx === 0;
                                return {
                                    text: String(cell),
                                    options: {
                                        fill: "FFFFFF", color: textColor,
                                        fontFace: mainFont, valign: "middle", bold: isFirstCol
                                    }
                                };
                            }));
                        });
                        const tableH = Math.min(3.5, 4.8 - cY);
                        slide.addTable(tableData, {
                            x: 0.5, y: cY, w: 9.0, h: tableH, rowH: 0.4,
                            fontSize: 13, border: { type: "solid", color: borderColor, pt: 1 }
                        });
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                case "chart-placeholder": {
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });

                    // ==========================================
                    // 1. リッチヘッダー
                    // ==========================================
                    const eyebrow = s.eyebrow || "DATA & INSIGHTS";
                    slide.addText(eyebrow, {
                        x: 0.5, y: 0.35, w: 4.5, h: 0.2,
                        fontSize: 11, fontFace: mainFont, bold: true, color: accentColor, charSpacing: 2
                    });
                    slide.addText(s.title || "データチャート", {
                        x: 0.5, y: 0.55, w: 4.5, h: 0.5,
                        fontSize: 28, fontFace: headerFont, bold: true, color: primaryColor
                    });
                    if (s.lead) {
                        slide.addText(s.lead, {
                            x: 5.2, y: 0.65, w: 4.3, h: 0.4,
                            fontSize: 13, fontFace: mainFont, color: textColor, align: "left", valign: "bottom", breakLine: true
                        });
                    }
                    slide.addShape(pptx.ShapeType.line, {
                        x: 0.5, y: 1.15, w: 9.0, h: 0,
                        line: { color: borderColor, width: 2 }
                    });

                    // ==========================================
                    // 2. 情報量（インサイト有無）に応じたレイアウト計算
                    // ==========================================
                    const hasInsight = !!s.insight;
                    const contentY = 1.4;
                    const contentH = 3.4; // 利用可能な高さ

                    const chartX = 0.5;
                    const chartY = contentY;
                    const chartH = contentH;
                    // インサイトパネルがあれば幅を削り、無ければ全幅にする
                    const chartW = hasInsight ? 5.6 : 9.0;

                    // ==========================================
                    // 3. カラーパレットの自動生成
                    // ==========================================
                    // プライマリカラーを起点に、徐々に明るくした同系色配列を生成
                    const generateChartColors = (baseHex, count) => {
                        const colors = [];
                        for (let i = 0; i < count; i++) {
                            // 2色目にアクセントカラーを混ぜて彩りを加える
                            if (i === 1 && accentColor && accentColor !== baseHex) {
                                colors.push(accentColor);
                            } else {
                                // 0%, 15%, 30%...と明度を上げる
                                colors.push(getGradientEndColor(baseHex, i * 0.15));
                            }
                        }
                        return colors.slice(0, count);
                    };

                    // ==========================================
                    // 4. グラフの描画
                    // ==========================================
                    if (s.series && s.categories) {
                        let pptxChartType = pptx.charts.BAR;

                        // モダンなグラフの共通ベース設定
                        let chartOpts = {
                            x: chartX, y: chartY, w: chartW, h: chartH,
                            showLegend: true,
                            // インサイトがある場合は下部、全幅の場合は右側に凡例を置くと美しい
                            legendPos: hasInsight ? 'b' : 'r',
                            chartColors: generateChartColors(primaryColor, Math.max(5, s.series.length)),
                            fontFace: mainFont,
                            valAxisLineShow: false, // 縦軸の線を消す
                            catAxisLineShow: true,
                            catAxisLineColor: borderColor,
                            valGridLineColor: borderColor,
                            valGridLineStyle: 'dash', // グリッドを点線に
                        };

                        // グラフタイプごとの個別チューニング
                        if (s.chartType === "line") {
                            pptxChartType = pptx.charts.LINE;
                            chartOpts.lineSize = 3;
                            chartOpts.lineDataSymbol = 'circle'; // マーカーを表示
                            chartOpts.lineDataSymbolSize = 6;
                        } else if (s.chartType === "pie") {
                            pptxChartType = pptx.charts.PIE;
                            chartOpts.legendPos = 'r'; // 円グラフは右側固定が見やすい
                        } else if (s.chartType === "doughnut") {
                            pptxChartType = pptx.charts.DOUGHNUT;
                            chartOpts.holeSize = 65; // 美しいドーナツ幅
                            chartOpts.legendPos = 'r';
                        } else if (s.chartType === "stacked-bar") {
                            pptxChartType = pptx.charts.BAR;
                            chartOpts.barGrouping = 'stacked';
                            chartOpts.barGapWidthPct = 40;
                        } else if (s.chartType === "horizontal-bar") {
                            pptxChartType = pptx.charts.BAR;
                            chartOpts.barDir = 'bar';
                            chartOpts.barGapWidthPct = 40;
                        } else {
                            // デフォルト (通常の棒グラフ)
                            chartOpts.barGapWidthPct = 40; // 棒の間隔を調整してスマートに
                        }

                        const chartData = s.series.map(ser => ({
                            name: ser.name,
                            labels: s.categories,
                            values: ser.values
                        }));

                        slide.addChart(pptxChartType, chartData, chartOpts);
                    }

                    // ==========================================
                    // 5. インサイト領域 (右側パネル)
                    // ==========================================
                    if (hasInsight) {
                        const insightX = 6.4; // グラフの右側に配置 (0.5 + 5.6 + gap 0.3)
                        const insightW = 3.1;

                        // パネル背景 (薄グレー)
                        slide.addShape(pptx.ShapeType.roundRect, {
                            x: insightX, y: contentY, w: insightW, h: contentH,
                            fill: { color: secondaryColor },
                            rectRadius: 0.05
                        });

                        // A. ピル型タグ
                        const tagText = s.insightTag || "KEY TAKEAWAY";
                        const tagW = Math.max(1.0, (tagText.length * 0.1) + 0.3);
                        slide.addShape(pptx.ShapeType.roundRect, {
                            x: insightX + 0.2, y: contentY + 0.2, w: tagW, h: 0.25,
                            fill: { color: primaryColor },
                            rectRadius: 0.12
                        });
                        slide.addText(tagText, {
                            x: insightX + 0.2, y: contentY + 0.22, w: tagW, h: 0.25,
                            fontSize: 9, fontFace: mainFont, bold: true, color: "FFFFFF", align: "center", valign: "middle", charSpacing: 1
                        });

                        let textY = contentY + 0.6;

                        // B. ハイライト数値
                        if (s.insightHighlight) {
                            // 大きな数値を配置
                            slide.addText(s.insightHighlight, {
                                x: insightX + 0.2, y: textY, w: insightW - 0.4, h: 0.5,
                                fontSize: 32, fontFace: 'Arial', bold: true, color: primaryColor, align: "left"
                            });
                            textY += 0.55;
                        }

                        // C. 区切り線
                        slide.addShape(pptx.ShapeType.line, {
                            x: insightX + 0.2, y: textY, w: insightW - 0.4, h: 0,
                            line: { color: borderColor, width: 1 }
                        });
                        textY += 0.15;

                        // D. インサイト本文
                        slide.addText(s.insight, {
                            x: insightX + 0.2, y: textY, w: insightW - 0.4, h: (contentY + contentH) - textY - 0.2,
                            fontSize: 13, fontFace: mainFont, color: textColor, align: "left", valign: "top", breakLine: true, lineSpacing: 18
                        });
                    }

                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;
                }

                case "workflow": {
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });

                    // ==========================================
                    // 1. リッチヘッダー
                    // ==========================================
                    const wfEyebrow = s.eyebrow || "PROCESS";
                    slide.addText(wfEyebrow, {
                        x: 0.5, y: 0.35, w: 4.5, h: 0.2,
                        fontSize: 11, fontFace: mainFont, bold: true, color: accentColor, charSpacing: 2
                    });
                    slide.addText(s.title || "ワークフロー", {
                        x: 0.5, y: 0.55, w: 4.5, h: 0.5,
                        fontSize: 28, fontFace: headerFont, bold: true, color: primaryColor
                    });
                    if (s.lead) {
                        slide.addText(s.lead, {
                            x: 5.2, y: 0.65, w: 4.3, h: 0.4,
                            fontSize: 13, fontFace: mainFont, color: textColor, align: "left", valign: "bottom", breakLine: true
                        });
                    }
                    slide.addShape(pptx.ShapeType.line, {
                        x: 0.5, y: 1.15, w: 9.0, h: 0,
                        line: { color: borderColor, width: 2 }
                    });

                    // ==========================================
                    // 2. ステップ配置の自動計算
                    // ==========================================
                    if (s.steps && s.steps.length > 0) {
                        const stepCount = s.steps.length;
                        const totalW = 9.0;
                        const arrowW = 0.3; // 矢印の幅
                        const gap = 0.2;   // カードと矢印の間の余白

                        // 1枚あたりのカード幅を計算
                        // 式: n*cardW + (n-1)*(arrowW + 2*gap) = totalW
                        const cardW = (totalW - (stepCount - 1) * (arrowW + gap * 2)) / stepCount;
                        const cardH = 3.2;
                        const startY = 1.6;

                        s.steps.forEach((step, i) => {
                            const x = 0.5 + i * (cardW + arrowW + gap * 2);

                            // A. ステップカード本体 (白背景・グレー枠)
                            slide.addShape(pptx.ShapeType.roundRect, {
                                x: x, y: startY, w: cardW, h: cardH,
                                fill: { color: "FFFFFF" },
                                line: { color: borderColor, width: 1 },
                                rectRadius: 0.05
                            });

                            // B. ステップ番号 (01, 02...)
                            const stepNum = String(i + 1).padStart(2, '0');
                            slide.addText(stepNum, {
                                x: x + 0.2, y: startY + 0.2, w: cardW - 0.4, h: 0.4,
                                fontSize: 24, fontFace: 'Arial', bold: true, color: primaryColor, align: "left"
                            });

                            // C. ステップタイトル
                            slide.addText(step.title || `Step ${i + 1}`, {
                                x: x + 0.2, y: startY + 0.7, w: cardW - 0.4, h: 0.4,
                                fontSize: 16, fontFace: headerFont, bold: true, color: primaryColor, align: "left", valign: "top"
                            });

                            // D. ステップ説明文
                            slide.addText(step.desc || "", {
                                x: x + 0.2, y: startY + 1.2, w: cardW - 0.4, h: cardH - 1.4,
                                fontSize: 12, fontFace: mainFont, color: textColor, align: "left", valign: "top", breakLine: true, lineSpacing: 18
                            });

                            // E. フロー矢印 (最後のステップ以外)
                            if (i < stepCount - 1) {
                                const arrowX = x + cardW + gap;
                                slide.addShape(pptx.ShapeType.rightArrow, {
                                    x: arrowX, y: startY + cardH / 2 - 0.15, w: arrowW, h: 0.3,
                                    fill: { color: borderColor }
                                });
                            }
                        });
                    }

                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;
                }

                case "closing": {
                    // タイトルスライドと同じグラデーション背景のマスターを使用
                    slide = pptx.addSlide({ masterName: "TITLE_SLIDE" });

                    const cardX = 1.2;
                    const cardY = 1.0;
                    const cardW = 7.6;
                    const cardH = 3.6;

                    // 1. センターカード (白背景・薄い枠線)
                    slide.addShape(pptx.ShapeType.roundRect, {
                        x: cardX, y: cardY, w: cardW, h: cardH,
                        fill: { color: "FFFFFF" },
                        line: { color: borderColor, width: 1 },
                        rectRadius: 0.05
                    });

                    // 2. Eyebrow (Closingタグ)
                    const closingEyebrow = s.eyebrow || "CLOSING";
                    slide.addText(closingEyebrow, {
                        x: cardX, y: cardY + 0.3, w: cardW, h: 0.3,
                        fontSize: 11, fontFace: mainFont, bold: true, color: accentColor,
                        align: "center", charSpacing: 2
                    });

                    // 3. メインタイトル (感謝のメッセージなど)
                    slide.addText(s.title || "ご清聴ありがとうございました", {
                        x: cardX + 0.5, y: cardY + 0.8, w: cardW - 1.0, h: 1.2,
                        fontSize: 34, fontFace: headerFont, bold: true, color: primaryColor,
                        align: "center", valign: "middle", breakLine: true
                    });

                    // 4. サブメッセージ (詳細な結びの言葉)
                    const subMessage = s.message || s.lead || "";
                    if (subMessage) {
                        slide.addText(subMessage, {
                            x: cardX + 0.8, y: cardY + 2.0, w: cardW - 1.6, h: 0.8,
                            fontSize: 14, fontFace: mainFont, color: textColor,
                            align: "center", valign: "top", breakLine: true, lineSpacing: 20
                        });
                    }

                    // 5. アクションピル (センタリング動的計算)
                    if (s.actions && s.actions.length > 0) {
                        const gap = 0.15;
                        const pillHeights = 0.35;
                        const pillY = cardY + 2.9;

                        // 各ピルの幅を文字数から概算 (1文字約0.13インチ + 左右パディング)
                        const pillWidths = s.actions.map(act => (act.length * 0.13) + 0.4);
                        // 全ピルの合計幅 + 間のギャップを計算
                        const totalPillsWidth = pillWidths.reduce((a, b) => a + b, 0) + (gap * (s.actions.length - 1));

                        // 開始X座標をカード中央に合わせるオフセット計算
                        let currentX = cardX + (cardW - totalPillsWidth) / 2;

                        s.actions.forEach((action, idx) => {
                            const pW = pillWidths[idx];

                            // ピル外枠
                            slide.addShape(pptx.ShapeType.roundRect, {
                                x: currentX, y: pillY, w: pW, h: pillHeights,
                                line: { color: borderColor, width: 1 },
                                rectRadius: 0.17
                            });
                            // ピルテキスト
                            slide.addText(action, {
                                x: currentX, y: pillY, w: pW, h: pillHeights,
                                fontSize: 10, fontFace: mainFont, color: accentColor,
                                align: "center", valign: "middle"
                            });

                            // 次のピルの位置へ移動
                            currentX += pW + gap;
                        });
                    }

                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;
                }

                case "feature-cards":
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "", "Features");
                    renderLead(slide, s.lead);

                    if (s.cards && s.cards.length > 0) {
                        const cardCount = s.cards.length;
                        const totalW = 9.0;
                        const gap = 0.3;
                        const cardW = (totalW - gap * (cardCount - 1)) / cardCount;
                        const cardH = 4.8 - cY;

                        s.cards.forEach((card, i) => {
                            const x = 0.5 + i * (cardW + gap);
                            slide.addShape(pptx.ShapeType.roundRect, {
                                x: x, y: cY, w: cardW, h: cardH,
                                fill: { color: secondaryColor }, line: { color: borderColor, width: 1 }, rectRadius: 0.08
                            });

                            // アイコン代わりのEyebrow
                            slide.addText(card.iconHint ? 'FEATURE' : 'FEATURE', {
                                x: x, y: cY + 0.3, w: cardW, h: 0.2,
                                fontSize: 10, color: primaryColor, align: "center", fontFace: mainFont, bold: true, charSpacing: 1
                            });

                            slide.addText(card.title, {
                                x: x + 0.2, y: cY + 0.6, w: cardW - 0.4, h: 0.4,
                                fontSize: 16, fontFace: headerFont, bold: true, color: primaryColor, align: "center"
                            });

                            slide.addText(card.description, {
                                x: x + 0.2, y: cY + 1.2, w: cardW - 0.4, h: cardH - 1.8,
                                fontSize: 13, fontFace: mainFont, color: textColor, align: "center", valign: "top", breakLine: true
                            });
                        });
                    }
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;

                default:
                    // フォールバック
                    slide = pptx.addSlide({ masterName: "DEFAULT_SLIDE" });
                    renderHeader(slide, s.title || "Slide", "Content");
                    renderLead(slide, s.lead);
                    slide.addText(`[対応中スライドタイプ: ${s.type}]`, {
                        x: 0.5, y: cY, w: 9.0, h: 1.0,
                        fontSize: 14, fontFace: mainFont, color: mutedColor, align: "center"
                    });
                    renderFooterNote(slide, s.footerNote);
                    if (s.speakerNotes) slide.addNotes(s.speakerNotes);
                    break;
            }
        });

        const safeTitle = (spec.documentTitle || 'presentation').replace(/[\\/:*?"<>|]/g, '_');
        logInfo(`Saving PPTX file: ${safeTitle}.pptx`);
        await pptx.writeFile({ fileName: `${safeTitle}.pptx` });
        logInfo('PPTX generation completed successfully.');
    } catch (e) {
        logError('Error during PPTX generation', e);
        throw e;
    }
};